version: '3.8'

services:
  java_app:
    container_name: java_app
    image: credi_java_app:1.0.0
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
    depends_on:
      - java_db
    networks:
      - net
  java_db:
    container_name: java_db
    image: postgres:16.0-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    networks:
      - net
networks:
  net: